version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nginx:
    image: nginx:alpine
    container_name: mynginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - djangonetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydjango
    volumes:
      - ./src:/src
    expose:
      - "8000"
    env_file:
      - ./.env
    networks:
      - djangonetwork


networks:
  djangonetwork:
    driver: bridge
